from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

from mathlab.manuscripts import latex_command, parse_manuscripts_manifest
from mathlab.reports import build_status_report, render_status_markdown, write_status_sources


class StatusReportTests(unittest.TestCase):
    def _state_root(self, directory: str) -> Path:
        root = Path(directory)
        state = root / "state"
        state.mkdir(parents=True)
        facts = [
            {"fact_id": "F-VERIFIED", "status": "VERIFIED"},
            {"fact_id": "F-PROPOSED", "status": "PROPOSED"},
            {"fact_id": "F-COMPUTATIONAL", "status": "DRAFT"},
        ]
        issues = [
            {"issue_id": "I-FATAL", "status": "OPEN", "severity": "FATAL"},
            {"issue_id": "I-FIXED", "status": "FIXED", "severity": "MAJOR"},
            {"issue_id": "I-MINOR", "status": "OPEN", "severity": "MINOR"},
        ]
        (state / "fact_graph.jsonl").write_text(
            "\n".join(json.dumps(value) for value in facts) + "\n", encoding="utf-8"
        )
        (state / "issue_ledger.jsonl").write_text(
            "\n".join(json.dumps(value) for value in issues) + "\n", encoding="utf-8"
        )
        (state / "project_state.json").write_text(
            json.dumps(
                {
                    "updated_at": "2026-07-29T00:00:00Z",
                    "current_objective": "Keep proof status separate from computation.",
                    "next_recommended_action": "Request independent verification.",
                    "proposed_results": ["F-PROPOSED remains proposed."],
                    "tasks_lacking_independent_verification": ["F-PROPOSED"],
                }
            ),
            encoding="utf-8",
        )
        return root

    def test_truth_derived_report_has_counts_blockers_and_stable_digest(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = self._state_root(temp)
            first = build_status_report(root)
            second = build_status_report(root)
            self.assertEqual({"DRAFT": 1, "PROPOSED": 1, "VERIFIED": 1}, first["counts"]["facts"])
            self.assertEqual({"FIXED": 1, "OPEN": 2}, first["counts"]["issues"])
            self.assertEqual(["I-FATAL"], first["open_blocking_issue_ids"])
            self.assertEqual(["F-VERIFIED"], first["facts_by_status"]["VERIFIED"])
            self.assertEqual(first["source_digest"], second["source_digest"])

    def test_bilingual_markdown_keeps_proposed_and_computational_distinct(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            report = build_status_report(self._state_root(temp))
            english = render_status_markdown(report, "en")
            chinese = render_status_markdown(report, "zh-TW")
            self.assertIn("PROPOSED", english)
            self.assertIn("DRAFT", english)
            self.assertIn("does not promote claims", english)
            self.assertIn("不會升格 claim", chinese)
            self.assertIn(report["source_digest"], chinese)

    def test_status_writer_emits_bilingual_markdown_and_tex(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = self._state_root(temp)
            templates = root / "paper" / "status_templates"
            templates.mkdir(parents=True)
            template = "\\documentclass{article}\n{{SOURCE_DIGEST}}\n{{FACTS_BY_STATUS}}\n"
            (templates / "status_en.tex.in").write_text(template, encoding="utf-8")
            (templates / "status_zh_TW.tex.in").write_text(template, encoding="utf-8")
            paths = write_status_sources(root)
            self.assertTrue(all(path.is_file() for path in paths.values()))
            canonical = paths["canonical_markdown"].read_text(encoding="utf-8")
            self.assertIn("GENERATED by mathlab.reports", canonical)
            self.assertIn("研究狀態", canonical)
            self.assertIn("F-VERIFIED", paths["markdown_en"].read_text(encoding="utf-8"))
            self.assertIn("F-PROPOSED", paths["tex_zh-TW"].read_text(encoding="utf-8"))

    def test_status_writer_preflights_all_templates_before_writing(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = self._state_root(temp)
            canonical = root / "state" / "STATUS.md"
            canonical.write_text("existing status\n", encoding="utf-8")
            templates = root / "paper" / "status_templates"
            templates.mkdir(parents=True)
            (templates / "status_en.tex.in").write_text(
                "{{SOURCE_DIGEST}}\n", encoding="utf-8"
            )

            with self.assertRaises(FileNotFoundError):
                write_status_sources(root)
            self.assertEqual("existing status\n", canonical.read_text(encoding="utf-8"))

    def test_status_renderer_rejects_unknown_locale(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            report = build_status_report(self._state_root(temp))
            with self.assertRaisesRegex(ValueError, "Unsupported status locale"):
                render_status_markdown(report, "unknown")


class ManuscriptManifestTests(unittest.TestCase):
    def _manifest_root(self, directory: str) -> Path:
        root = Path(directory).resolve()
        paper = root / "paper"
        paper.mkdir(parents=True)
        (paper / "references.bib").write_text("% shared bibliography\n", encoding="utf-8")
        (paper / "manuscript_en.tex").write_text("\\documentclass{article}\n", encoding="utf-8")
        (paper / "manuscript_zh.tex").write_text("\\documentclass{article}\n", encoding="utf-8")
        (paper / "manuscripts.yml").write_text(
            """version: 1
output_directory: dist/pdf
manuscripts:
  - id: research-progress-en
    locale: en
    source: paper/manuscript_en.tex
    engine: pdflatex
    claim_map: paper/claim_map.yml
    bibliography: paper/references.bib
    output: manuscript_en.pdf
  - id: research-progress-zh-tw
    locale: zh-TW
    source: paper/manuscript_zh.tex
    engine: xelatex
    claim_map: paper/claim_map.yml
    bibliography: paper/references.bib
    output: manuscript_zh.pdf
""",
            encoding="utf-8",
        )
        (paper / "claim_map.yml").write_text("claims: []\n", encoding="utf-8")
        return root

    def test_manifest_parses_bilingual_entries_and_shared_bibliography(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = self._manifest_root(temp)
            specs = parse_manuscripts_manifest(root / "paper" / "manuscripts.yml", root=root)
            self.assertEqual(["research-progress-en", "research-progress-zh-tw"], [spec.identifier for spec in specs])
            self.assertEqual(["pdflatex", "xelatex"], [spec.engine for spec in specs])
            self.assertEqual({spec.bibliography for spec in specs}, {root / "paper" / "references.bib"})
            self.assertEqual({spec.claim_map for spec in specs}, {root / "paper" / "claim_map.yml"})

    def test_manifest_rejects_a_final_pdf_directory_outside_dist_pdf(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = self._manifest_root(temp)
            manifest = root / "paper" / "manuscripts.yml"
            manifest.write_text(
                manifest.read_text(encoding="utf-8").replace("output_directory: dist/pdf", "output_directory: output/pdf"),
                encoding="utf-8",
            )
            with self.assertRaisesRegex(ValueError, "output_directory"):
                parse_manuscripts_manifest(manifest, root=root)

    def test_latex_command_keeps_auxiliaries_in_build_pdf(self) -> None:
        with tempfile.TemporaryDirectory() as temp:
            root = self._manifest_root(temp)
            spec = parse_manuscripts_manifest(root / "paper" / "manuscripts.yml", root=root)[0]
            command = latex_command(spec, root / "build" / "pdf")
            self.assertEqual("pdflatex", command[0])
            self.assertIn("-halt-on-error", command)
            self.assertIn(f"-output-directory={(root / 'build' / 'pdf').resolve()}", command)
            self.assertEqual("manuscript_en.tex", command[-1])


if __name__ == "__main__":
    unittest.main()
